### ISSUE TITLE
bundler fails on complicated include guards

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#191]
``` c++
#pragma once
#ifndef call_from_test
#include<bits/stdc++.h>
using namespace std;
#endif
//BEGIN CUT HERE
int expression(string,int&);
int term(string,int&);
int factor(string,int&);
int number(string,int&);
```

``` python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 347, in write_contents
    bundled_code = language.bundle(self.file_class.file_path, basedir=self.cpp_source_path)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/languages/cplusplus.py", line 68, in bundle
    bundler.update(path)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/languages/cplusplus_bundle.py", line 151, in update
    raise BundleError(path, i + 1, "found codes out of include guard")
onlinejudge_verify.languages.cplusplus_bundle.BundleError: string/parse.cpp: line 6: found codes out of include guard
```

https://github.com/beet-aizu/library/blob/8f0656dae1fb615535bffc55bbe66b2edf8b0e24/string/parse.cpp#L1-L10

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr"><a href="https://twitter.com/hashtag/pragma?src=hash&amp;ref_src=twsrc%5Etfw">#pragma</a> onceをつけてもbundleできない、一体どういう仕様なんだ</p>&mdash; beet (@beet_aizu) <a href="https://twitter.com/beet_aizu/status/1235571588956745728?ref_src=twsrc%5Etfw">March 5, 2020</a></blockquote>

**Comment by kmyk** [comment]
include guard には `#ifndef HOGE_H #define HOGE_H ... #endif` の形式と `#pragma once` の形式とがあるが、両方同時に使われてると誤認識してるように見える

参考: <https://ja.wikibooks.org/wiki/More_C%2B%2B_Idioms/%E3%82%A4%E3%83%B3%E3%82%AF%E3%83%AB%E3%83%BC%E3%83%89%E3%82%AC%E3%83%BC%E3%83%89%E3%83%9E%E3%82%AF%E3%83%AD(Include_Guard_Macro)>
